### PR TITLE
Added code to remove authority from species name

### PR DESCRIPTION
**Pull request by BenMerSci**

### CODE REVIEW

**Review by scisus — CHANGES_REQUESTED** [review]
This script is part of a toy version of the analysis with just Toronto. 

Like gbifDL, we can then use this tiny analysis as a template for the larger.

We should not include all of the cities here.

**Comment by BenMerSci** [comment]
Oh okok. I would propose though we start doing all the analysis on everything and scripting the final things already since its due in less than a week. That's why i put everything in there.

Like when we script and it works, it's all the same for every city so i'd suggest we just put it all in there.

**Comment by BenMerSci** [comment]
And my bad for the script gbifDL.r, didn't realize it was part of the tiny analysis pipeline. (It has all the cities in it now..)

**Comment by scisus** [comment]
I agree that we need to scale to other cities quickly - I was trying to avoid having to rewrite so much if we needed to go back and change things. But you're right that, for these steps especially, it should be fine. I'll rename this file to be more accurate.

**Pull request merged**
